### ISSUE TITLE
OpenTelemetry: support metrics

### ISSUE THREAD

**Issue by arjun-1** [zio/zio-telemetry#131]
OpenTelemetry also allows to report metrics:

- https://github.com/open-telemetry/opentelemetry-java/blob/master/QUICKSTART.md#metrics
- https://github.com/open-telemetry/opentelemetry-specification/tree/master/specification/metrics

zio-telemetry doesn't support these, but could potentially

**Comment by grouzen** [comment]
@arjun-1 Thanks for adding this issue. We will add support for it soon!

**Comment by grouzen** [comment]
Working on this one.
