### ISSUE TITLE
OpenTracing: Tags are set on parent span

### ISSUE THREAD

**Issue by Fristi** [zio/zio-telemetry#132]
When doing this

```scala
other
        .send(request.headers(headers.toMap))
        .span(show"${request.method.method} ${request.uri.path.mkString("/")}")
        .tag("span.kind", "client")
        .tag("http.method", request.method.method)
        .tag("http.url", request.uri.toString())
        .tag("type", "ext")
        .tag("subtype", "http")
        .flatMap(res => OpenTracing.tag("http.status_code", res.code.code) *> ZIO.succeed(res))
```

The `tag` are not set on the span of `send` but on it's parent.

**Comment by runtologist** [comment]
The span of `send` does not exist at the time you set the tag. `tag` is not a method on span. It ist a method on ZIO, which reads the current span and tags it. Move the `span` to the line before `flatMap` and it will do what you expect.

**Comment by runtologist** [comment]
@Fristi, does the proposed fix help, or do we need to investigate this further?

**Comment by Fristi** [comment]
It helped, I contributed this to sttp btw https://sttp.softwaremill.com/en/latest/backends/wrappers/zio-opentracing.html
