### ISSUE TITLE
Support for opentelemetry-api v0.9+

### ISSUE THREAD

**Issue by easel** [zio/zio-telemetry#257]
There are have been some breaking changes in the upstream api for opentelemetry tracing. Most notably, `BREAKING CHANGE: The only way to specify span parenting is via a parent Context` from https://github.com/open-telemetry/opentelemetry-java/releases/tag/v0.9.1

Has anyone given any thought as to how to adjust zio-telemetry to match yet?

**Comment by runtologist** [comment]
AFAIK not. PRs would be highly appreciated.

**Comment by easel** [comment]
Ok. I have hacked at making things compile a little bit locally but I'm not sure how it will impact usability -- basically every usage of Span has to be replaced with Context.

**Comment by duxet** [comment]
> Ok. I have hacked at making things compile a little bit locally but I'm not sure how it will impact usability -- basically every usage of Span has to be replaced with Context.

I've left Spans in my PR, as they can be easily injected/extracted from Context. I think it would make more sense to make such switch in a separate PR if it would needed, eg. for sharing baggage with logging/metrics.

**Comment by runtologist** [comment]
I think it's a good idea to upgrade while leaving the API mostly intact and making a switch separately. 

We might also want to do an intermediate release introducing the new API and deprecating the existing one.

**Comment by easel** [comment]
I agree, the approach you've taken keeps the change surface much more reasonable for consumers. Frankly, if we were going to change up the API, I think I'd go consider going the route of decoupling from any implementation entirely in favor of a "native" interface with adapters to opentracing/opentelemetry on the backend.

**Comment by runtologist** [comment]
Closing this issue as the upgrade is done. I propose continuing discussion about API in #194.
