### ISSUE TITLE
Publish opencensus package

### ISSUE THREAD

**Issue by pettermachado** [zio/zio-telemetry#292]
I am trying to use zio-opencensus using the following dependency

```
"dev.zio" %% "zio-opencensus" % "0.7.0"
```
but get the following error when running `sbt update`

```
[error] sbt.librarymanagement.ResolveException: Error downloading dev.zio:zio-opencensus_2.13:0.7.0
[error]   Not found
[error]   Not found
[error]   not found: /home/petter/.ivy2/local/dev.zio/zio-opencensus_2.13/0.7.0/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/dev/zio/zio-opencensus_2.13/0.7.0/zio-opencensus_2.13-0.7.0.pom
...
```

It looks like zio-opencensus is not published at all in the `sbt ci-release` command, but I am not really sure where and how that is configured. Anyway, I would appreciate if zio-opencensus could get published.

**Comment by mijicd** [comment]
Resolved in #294
