### ISSUE TITLE
Scala 3

### ISSUE THREAD

**Issue by francisdb** [zio/zio-telemetry#377]
Is a Scala 3 release planned?
What are the roadblocks?

**Comment by runtologist** [comment]
A Scala 3 release would be great. I guess the only change necessary is extending the build configuration. A PR would be highly appreciated.

**Comment by mvelimir** [comment]
I will work on this.

**Comment by mvelimir** [comment]
There is a type mismatch error when compiling the opentracing tests. Opentelemetry tests pass just fine. Also, some of the libraries used in the example applications don't have Scala 3 support, such as zio-config-magnolia, zio-magic and zio-json from sttp.client3.

**Comment by francisdb** [comment]
@mvelimir found related scala 3 tickets on those projects?
