### ISSUE TITLE
Rewrite examples using ZIO libraries

### ISSUE THREAD

**Issue by mijicd** [zio/zio-telemetry#402]
With zio-config, zio-json and zio-http out there, it makes sense to rewrite the OpenTracing and OpenTelemetry examples using them. 

For the sake of simplicity, the implementer should preserve the existing scenario, i.e., server and client, tracing the whole request-response cycle. Once the examples are ported, we can think about making additional scenarios.

**Comment by mijicd** [comment]
cc @mvelimir

**Comment by mvelimir** [comment]
I will work on this.
