### ISSUE TITLE
Need a more flexible API to set StatusCode

### ISSUE THREAD

**Issue by tuleism** [zio/zio-telemetry#444]
Currently all APIs accept a `toErrorStatus: PartialFunction[E, StatusCode]` and then set the `Span`'s `Status` like this:

https://github.com/zio/zio-telemetry/blob/d59c6a7d4a7cdce95e30cbe9788fc27e1f13b794/opentelemetry/src/main/scala/zio/telemetry/opentelemetry/Tracing.scala#L46-L53

The default is `Map.empty`, meaning that for any defect or failure, we set the `Span`'s `StatusCode` to `UNSET`, together with a `Description`. IMO there a a few problems:

- It is a bit confusing: According to the [specification](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status), `Description` is optional (for example: [Don't set the span status description](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status) if the reason can be inferred from `http.status_code`) and MUST only be used with the `Error` `StatusCode` value.
- Unless the operation contains an error, the `StatusCode` should remain "unset" and attempts to set value `Unset` will be ignored. A more sensible default would be to always set an `Error` `StatusCode` for any defect or failure and allow the caller to change if needed.
- Sometimes, for a `ZIO[R, E, A]`, we also want to set `StatusCode` based on `A`. For example, the [OpenTelemetry's semantic conventions for HTTP recommends](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/http.md#status) to set `StatusCode` `Error` for HTTP status codes in the 4xx and 5xx ranges. So in this case, we need to look into a  "successful" response to know which `StatusCode` to set.

For example, if we change the default, we can use something like `toErrorStatus: Either[E, A] => UIO[Any]` with a default that set `StatusCode` to `Error`, with a `Description`, for any defect or failure. 

WDYT?

**Comment by grouzen** [comment]
Good stuff! I'm considering splitting this into subtasks and fix in the near future. Thanks for posting this!

**Comment by grouzen** [comment]
Closing this one
