### ISSUE TITLE
Need a way to set the context from non-zio land

### ISSUE THREAD

**Issue by adrian-salajan** [zio/zio-telemetry#489]
We are starting the context from a graphQL API ( or even earlier in case of distributed tracing, from the client). I didn't know how to pass the context to the zio managed one via the FiberRef other than writing the below class in our project so I can access the package protected setters.

Is there a way to already to this ? else I think something should be available to pass an existing context inside the zio managed one

```
package zio.telemetry.opentelemetry

import io.opentelemetry.context.Context
import zio.ZIO

object ZioTelemetryAccessor {

  def setCurrent(ctx: Context): ZIO[Tracing, Nothing, Unit] = for {
    fib <- ZIO.access[Tracing](_.get.currentContext)
    _   <- fib.set(ctx)
  } yield ()

}
```

**Comment by grouzen** [comment]
@adrian-salajan Is this issue still actual for you? 

I'm not sure you need to pass the whole context. Instead, I suggest using external span as a parent for the span managed by `zio-telemetry`. For this, there is a method `Tracing.spanFromUnsafe`.
