### ISSUE TITLE
Not compatible with ZIO 2.0-RC3

### ISSUE THREAD

**Issue by francisdb** [zio/zio-telemetry#508]
Scala `3.1.1` with `-Yexplicit-nulls`
zio-opentelemetry 2.0.0-RC1

when upgrading from zio `2.0.0-RC2` to `2.0.0-RC3` we have the compiler throwing 

```
java.lang.AssertionError: assertion failed while compiling /foobar/tests/src/main/scala/tracing.scala
[error] ## Exception when compiling 1 sources to /foobar/tests/target/scala-3.1.1/classes
[error] java.lang.AssertionError: assertion failed
[error] scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:11)
[error] dotty.tools.dotc.core.Types$MethodType.<init>(Types.scala:3697)
[error] dotty.tools.dotc.core.Types$CachedMethodType.<init>(Types.scala:3717)
[error] dotty.tools.dotc.core.Types$MethodTypeCompanion.apply(Types.scala:3788)
[error] dotty.tools.dotc.core.Types$MethodTypeCompanion.apply(Types.scala:3787)
[error] dotty.tools.dotc.core.Types$LambdaType.newLikeThis(Types.scala:3470)
[error] dotty.tools.dotc.core.Types$LambdaType.newLikeThis$(Types.scala:3403)
[error] dotty.tools.dotc.core.Types$MethodOrPoly.newLikeThis(Types.scala:3483)
...
```

Single file with single line

**src/main/scala/tracing.scala**
```scala
val y = zio.telemetry.opentelemetry.Tracing.live
```

**build.sbt**
```scala
scalaVersion := "3.1.1"

scalacOptions ++= Seq(
  "-unchecked",
  "-deprecation",
  "-feature",
  "-Yexplicit-nulls",
  "-source",
  "future"
)

libraryDependencies ++= Seq(
  "dev.zio" %% "zio"               % "2.0.0-RC3",
  "dev.zio" %% "zio-opentelemetry" % "2.0.0-RC1"
)
```

**Comment by adamgfraser** [comment]
Okay, so this is a situation where a dependency is not compiled against a compatible ZIO version so I think the expectation is that this is not going to compile and I don't think we can make any guarantees regarding what the compiler error message will be. If this error message is worse when you use automatic layer construction versus manual layer construction then perhaps there is something we can do in the layer construction macro but otherwise I think you just have to wait for compatible dependencies.

**Comment by francisdb** [comment]
There's a big difference between not compiling and the compiler throwing a `AssertionError`

**Comment by vladimir-lu** [comment]
I already started the work for bringing an RC3 compatible version in https://github.com/zio/zio-telemetry/pull/509 - it's waiting on the zio-http module right now

**Comment by runtologist** [comment]
Thanks to the work of @vladimir-lu there is a brand new v2.0.0-RC2, which adds compatibility with ZIO 2.0.0-RC4 and all the goodness like getting rid of ZManaged and simplifying the Environment.
