### ISSUE TITLE
Integrate into ZIO Logging & Metrics

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-telemetry#558]
The goal of ZIO Telemetry should be to seamlessly add OpenTelemetry support via ZIO's own built-in logging and metrics, adding integration points as necessary and useful.

TODO

 - [x] How to map ZIO logging + annotations + other context to OpenTelemetry traces
 - [x] How to map ZIO logging + annotations + other context to OpenTelemetry logs
 - [x] How to map ZIO metrics to OpenTelemetry metrics
 - [x] How to map ZIO context + annotations to OpenTelemetry baggage

**Comment by easel** [comment]
These goals sound incredible. What's less clear to me is how complete the coverage is in native ZIO capabilities. I know ZIO has some "tracing" capabilities but am much less clear what they are and how well they map to the equivalent Otel concepts. @jdegoes any suggestions as to how we can get starting mapping these capabilities?

**Comment by grouzen** [comment]
I'm integrating Baggage with ZIO log annotations in this PR: https://github.com/zio/zio-telemetry/pull/662

**Comment by omidb** [comment]
is there any update on this?

**Comment by grouzen** [comment]
Hey! I'm still working on adding metrics support in general.  After this, I believe mapping ZIO metrics to OTEL metrics should be possible. 

The only part that was done long ago is mapping ZIO annotations to OpenTelemetry baggage. It is not reflected in docs, though, but you can check out the source code at https://github.com/zio/zio-telemetry/blob/series/2.x/opentelemetry/src/main/scala/zio/telemetry/opentelemetry/baggage/Baggage.scala and find some examples in https://github.com/zio/zio-telemetry/blob/series/2.x/opentelemetry/src/test/scala/zio/telemetry/opentelemetry/baggage/BaggageTest.scala#L89.

I was researching how to map ZIO logging and I don't think it is doable since there is no way to extract the original log message. I hope I am wrong about it.
Mapping annotations to traces and logs is also possible.

**Comment by omidb** [comment]
@grouzen thanks for the update. I'm trying to understand how does this work with something like `myzio.logError()`. Should I `tapError` and then create a Baggage? something like this: `.tapError(e => baggage.set("some", e.getMessage))`

**Comment by grouzen** [comment]
@omidb Yes, your solution is fine. As I said in the message above, there is no integration with ZIO logging at the moment and I don't think it is possible to make it happen due to technical reasons.

**Comment by grouzen** [comment]
Also, I've got another idea that we can potentially implement some sort of `otel-bridge` as a module of `zio-logging` library, which will use `zio-telemetry` as a backend, so the end user would be able to call `ZIO.log*` methods that will be sending logs to OTEL collector.

**Comment by grouzen** [comment]
@omidb Hello! The support for the Logs signal has been added recently, you can find it in the latest 3.0.0-RC-18 release version.

**Comment by grouzen** [comment]
Support for metrics has been added at #790

**Comment by omidb** [comment]
@grouzen thanks for the update. we will check this out. is there an example or doc?

**Comment by grouzen** [comment]
@omidb Of course! The docs were updated as well: https://zio.dev/zio-telemetry/opentelemetry/#logging 
If you have any questions after reading the docs, please do not hesitate to ask them in the Discord channel.

**Comment by omidb** [comment]
@grouzen thanks. not related to this issue, I was wondering what do u use for visualizing all the traces, logs, metrics? do u have a favorite all in one ecosystem?

**Comment by grouzen** [comment]
@omidb I'm planning to add an example for [Honeycomb](https://www.honeycomb.io/). They have a nice free plan. It is enough to run the example and see good-looking visualized results in one place. Related issue: https://github.com/zio/zio-telemetry/issues/791

**Comment by omidb** [comment]
@grouzen we use honeycomb internally. I want to find a good open source platform that does logging, tracing and metric all together. https://skywalking.apache.org/ looks interesting but it's not OTEL first and seems I have to go through hoops to get it to work.

**Comment by grouzen** [comment]
@omidb Sorry, do you mean Honeycomb doesn't provide a UI for all metrics? Yeah, Apache Skywalking could be a good option, but I also decided not to spend time on it for the same reason as yours.

**Comment by omidb** [comment]
@grouzen Honeycomb is limited to tracing and not a good log explorer. We can continue this discussion on Discord :)

**Comment by grouzen** [comment]
@omidb, As far as I know, DD provides a free plan, and it fits these requirements well. Moreover, there were many requests in the Discord channel to add an example for it :). The issue for adding a DD example: https://github.com/zio/zio-telemetry/issues/690

**Comment by grouzen** [comment]
Closing this one since all goals have been achieved.
