### ISSUE TITLE
Example App

### ISSUE THREAD

**Issue by runtologist** [zio/zio-telemetry#6]
We should illustrate use of zio-telemetry using an example app. It should consist of multiple HTTP services depending on each other. The first service should inject the trace context to all requests it makes. The other services extract and propagate that information. While a first version could just log tracing information, it would be nice to spin up a container running an actual opentracing collector, such as Jaeger to collect data.

* [x] Build at least two services
* [ ] Inject / Extract tracing headers
* [x] Log traces
* [x] Collect traces in Jaeger

**Comment by runtologist** [comment]
Jaeger provides an all in one Docker image using in memory storage for testing here: https://www.jaegertracing.io/docs/1.6/getting-started/#all-in-one-docker-image

**Comment by drmarjanovic** [comment]
@bblagojevic94 and I will take all of this.

**Comment by runtologist** [comment]
Awesome. Let me know, if I can help.
