### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by ioleo** [zio/zio-telemetry#674]
We need to add Scala 3 cross-compilation

**Comment by grouzen** [comment]
I believe we already have it: https://github.com/zio/zio-telemetry/blob/series/2.x/.github/workflows/ci.yml#L63

**Comment by ioleo** [comment]
Hmm... when I was searching on [maven](https://central.sonatype.com/search?q=zio-telemetry&namespace=dev.zio) for `zio-telemetry_3` nothing popped up. Now I see however that `zio-opentelemetry_3`, `zio-opencensus_3` etc are there.

Does this mean the README is out-of-date?

```
In order to use this library, we need to add the following line in our build.sbt file if we want to use [OpenTelemetry](https://opentelemetry.io/) client:

libraryDependencies += "dev.zio" %% "zio-telemetry" % "3.0.0-RC7"

And for using [OpenTracing](https://opentracing.io/) client we should add the following line in our build.sbt file:

libraryDependencies += "dev.zio" %% "zio-opentracing" % "3.0.0-RC7"
```

**Comment by grouzen** [comment]
Yeah, it looks like we have the wrong artifact names in README. Good catch, thanks! I'll fix it ASAP.
