### ISSUE TITLE
OpenTelemetry: Feeding telemetry into DataDog

### ISSUE THREAD

**Issue by grouzen** [zio/zio-telemetry#686]
The question was asked in the Discord channel (https://discord.com/channels/629491597070827530/639825316021272602/1082410092852416642):

> Hey all! I wanted to ask about the status of ZIO 2.x w/ zio-telemetry & feeding tracing info into Datadog. Most of the previous conversation in this channel revolves around ZIO 1.x. It's also my understanding that automatic instrumentation does not yet work with DataDog/dd-trace-java for ZIO 2.x (though there is a PR open here: https://github.com/DataDog/dd-trace-java/pull/4848)
> 
> Is manual instrumentation possible here, or is the reliance of DD's tracer on ThreadLocal for scope state breaking? If it is possible, does anyone have a preexisting example? I've only been able to locate the Jaeger example so far.

**Comment by grouzen** [comment]
One more related Discord thread: https://discord.com/channels/629491597070827530/639825316021272602/1161591495598551061

**Comment by grouzen** [comment]
Closing this one as we have https://github.com/zio/zio-telemetry/issues/690

**Comment by jivanic-demystdata** [comment]
FYI, I just made a new micro-lib to help you configure zio-opentelemetry to work with the Datadog APM: https://x.com/guizmaii/status/1806702414063612123
