### ISSUE TITLE
OpenTelemetry: find a way to avoid specifying type parameters when calling Tracing aspects

### ISSUE THREAD

**Issue by grouzen** [zio/zio-telemetry#733]
It is quite annoying that we need to pay the price of typing useless type annotations each time we call `zio @@ span[Throwable, Unit]("...")` or similar aspect methods when initially the goal of introducing them was to have better API ergonomics. 
We ended up in a situation where some of the methods require typing 3 type parameters after https://github.com/zio/zio-telemetry/pull/702 gets merged.

**Comment by regiskuckaertz** [comment]
Hello - I started using the library recently and definitely agree. Not necessarily related to type parameters, but one thing I wanted to suggest is that tracing _is_ an aspect, and therefore the API should just expose aspects without much boilerplate (a good inspiration is the `zio.Metric` API).

As for type parameters, I suggest to embrace variance, e.g. this compiles fine:
```scala
case class ErrorMapper[-E](body: PartialFunction[E, StatusCode], toThrowable: Option[E => Throwable] = None)
// ^ contravariant E

object ErrorMapper {
  val default: ErrorMapper[Any] = ErrorMapper(PartialFunction.empty)
  // ^ matches any type of error
}

trait Tracing {
  def inSpan[E](
    spanName: String,
    errorMapper: ErrorMapper[E] = ErrorMapper.default,
  ): ZIOAspect[Nothing, Any, E, Any, Nothing, Any]
  // ^ note we only set the lower bound for the error type, as an ErrorMapper[E] can handle
  // any error that is a supertype of E
}

def effect1: IO[Int, String] = ???

def effect2: IO[Throwable, Boolean] = ???

def effect3 = for {
  tracing <- ZIO.service[Tracing]
  _ <- effect1 @@ tracing.inSpan("Hello")
  _ <- effect2 @@ tracing.inSpan("No type params!")
} yield ()
```

Going further, you can move the aspects into the companion object so as to write:

```scala
object Tracing {
  def inSpan[E](
    spanName: String,
    errorMapper: ErrorMapper[E] = ErrorMapper.default,
  ): ZIOAspect[Nothing, Tracing, E, Any, Nothing, Any] =
  // ^ Here the upper bound of R is Tracing since we need to extract it
    new ZIOAspect[Nothing, Tracing, E, Any, Nothing, Any] {
      def apply[R <: Tracing, E0 >: E, A](zio: ZIO[R, E0, A])(implicit trace: Trace): ZIO[R, E0, A] =
        for {
          tracing <- ZIO.service[Tracing]
          a <- zio @@ tracing.inSpan(spanName, errorMapper)
        } yield a
    }
}

def effect3 = for {
  _ <- effect1 @@ Tracing.inSpan("Hello")
  _ <- effect2 @@ Tracing.inSpan("No type params!")
} yield ()
// ^ inferred type ZIO[Tracing, Any, Unit] (since lub for error is between Int and Throwable, it's Any)
```

I can play around with this if you're happy with the direction.

**Comment by grouzen** [comment]
Hello! 
I like the idea of using variance, haven't thought about it before.

> Going further, you can move the aspects into the companion object so as to write:

I'm not sure about it actually since the idea of migrating to ZIO module pattern 2.0 was getting rid of accessor methods (I coordinated this design decision along with introducing  `aspects` object inside `Tracing`  with John) and, as a result, we would like to use `tracing` instance everywhere instead of context-aware accessor-like API (`Tracing.inSpan` as an example).

**Comment by regiskuckaertz** [comment]
@grouzen fair enough! Check out #734 In the first commit I just apply the variance parameters, that simplifies a lot. In the second commit I have improved the type inference for the aspects with two options:

- opencensus: turning `Function1`s into `ZIOAspect`, so now you can just write 

```
ZIO.serviceWithZIO[Tracing] { tracing =>
  import tracing.*
  zio @@ inSpan(...)
}
```

That helps to remove a lot of type parameters in the definition of the trait:
```
trait Tracing {
  def span[E](
    name: String,
    kind: Span.Kind = Span.Kind.SERVER,
    toErrorStatus: ErrorMapper[E] = ErrorMapper.default,
    attributes: Map[String, AttributeValue] = Map.empty
  ): ZIOAspect[Nothing, Any, Nothing, E, Nothing, Any]
}
```

- in opentelemetry I keep everything as-is, but you need to add some type parameters to guide the inference:

```
trait Tracing {
def extractSpan[C, R, E, E1 <: E, A, A1 <: A](
    propagator: TraceContextPropagator,
    carrier: IncomingContextCarrier[C],
    spanName: String,
    spanKind: SpanKind = SpanKind.INTERNAL,
    attributes: Attributes = Attributes.empty(),
    statusMapper: StatusMapper[E, A] = StatusMapper.default,
    links: Seq[SpanContext] = Seq.empty
  )(zio: => ZIO[R, E1, A1])(implicit trace: Trace): ZIO[R, E1, A1]
}
```

Let me know what you prefer, happy either way 🕺

**Comment by grouzen** [comment]
@regiskuckaertz Hey! I like the approach you used in opentelemetry because it makes using aspects optional. Honestly, I wouldn't say I like choosing aspects-only way. Anyway, it is such a great improvement. Thanks for the contribution!

**Comment by regiskuckaertz** [comment]
@grouzen happy to help :-) I have applied the second pattern everywhere
