### ISSUE TITLE
Any reporters other than Zipkin reporter?

### ISSUE THREAD

**Issue by SimunKaracic** [zio/zio-telemetry#740]
The examples currently use the following for creating spans 
```
    "io.zipkin.reporter2"           % "zipkin-reporter"       % "2.16.3",
```

But we've run into[ this bug ](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/16530)when using it with Tempo.
My 2 options now are:
* contribute to the opentelemetry exporter and fix the bug
* try out some other reporters

Any ideas on different reporters I could try?

**Comment by grouzen** [comment]
Hello! First, I would like to clarify what module this question is about? Are you using `zio-opentracing`? And what is Tempo? Could you please share some link to it?

Update: found what is Tempo: https://grafana.com/oss/tempo/

**Comment by SimunKaracic** [comment]
Ah, sorry. It's about zio-opentracing.
The only example I found uses a JaegerTracer with a ZipkinV2Reporter.
Like so:
```
    val tracer = new Configuration(serviceName).getTracerBuilder
      .withSampler(new ConstSampler(true))
      .withReporter(new ZipkinV2Reporter(AsyncReporter.create(senderBuilder.build)))
      .build
```

I am wondering which reporters I can swap this one out with.

**Comment by grouzen** [comment]
@SimunKaracic So, do I understand correctly that you're sending data via Zipkin reporter to the OTEL collector? I mean, if that's the case, the better solution would be to instrument your application with `zio-opentelemetry`. In that case, you'll be using OTEL exporter directly.

**Comment by grouzen** [comment]
I think we can close this issue.
