### ISSUE TITLE
Opentelemetry-example doesn't collect data to Jaeger and Seq

### ISSUE THREAD

**Issue by IvanFinochenko** [zio/zio-telemetry#832]
I run scripts from opentelemetry-example.md, open Jaeger UI and Seq UI and don't see any data.

**Comment by grouzen** [comment]
Did you change the providers? 
There are different tracing and logging providers available:
- https://github.com/zio/zio-telemetry/blob/series/2.x/opentelemetry-example/src/main/scala/zio/telemetry/opentelemetry/example/otel/TracerProvider.scala
- https://github.com/zio/zio-telemetry/blob/series/2.x/opentelemetry-example/src/main/scala/zio/telemetry/opentelemetry/example/otel/LoggerProvider.scala

By default, we use stdout for the examples.
There is a line in the doc that explains this: https://github.com/zio/zio-telemetry/blob/series/2.x/docs/opentelemetry-example.md?plain=1#L35
Perhaps the documentation regarding this part is not written in the best way.

**Comment by IvanFinochenko** [comment]
@grouzen Thanks for answer. I have opened PR with some fix
